FROM postgres

ENV POSTGRES_PASSWORD postgres
ENV POSTGRES_DB psqldb

WORKDIR /usr/repos/postgresql

# Copy src directory for running on DB
# COPY ./src ./src
# Copy init.sql file in src directory to run on creation of container
# COPY src/init.sql /docker-entrypoint-initdb.d/
